In [1]:
import numpy as np
import math

# empty()

In [3]:
np.empty((5,6))

array([[8.90681208e-312, 8.90673898e-312, 0.00000000e+000,
        0.00000000e+000, 7.56599806e-307, 1.16097020e-028],
       [1.26104862e-076, 2.80061839e-028, 3.53356228e-057,
        1.04917183e-153, 5.23081515e-143, 1.46420733e-075],
       [3.85602389e-057, 6.82362948e-038, 2.87922738e+180,
        1.70098498e+256, 5.49109388e-143, 1.06396443e+224],
       [3.96041428e+246, 1.16318408e-028, 2.62201332e+180,
        5.99385529e-038, 4.18126645e-062, 1.49086608e+161],
       [1.01848862e+248, 1.16096643e-028, 9.80058441e+252,
        7.50189709e+247, 1.14484251e+243, 2.59903827e-144]])

In [4]:
np.empty((5,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        4.00539777e-307],
       [7.56599807e-307, 8.90104239e-307, 1.24610383e-306,
        1.69118108e-306],
       [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
        1.29062229e-306],
       [1.60217812e-306, 1.37961370e-306, 1.69118515e-306,
        1.11258277e-307],
       [1.05700515e-307, 1.11261774e-306, 1.29060871e-306,
        8.34424766e-308]])

In [8]:
np.empty((3,3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 8.26077760e-321],
       [8.45603440e-307, 4.45046007e-307, 2.37667058e-312]])

# Reshaping an Array using reshape() method

In [10]:
# Reshaping an Array
# Reshape function creates a new object
a =np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
print(a.shape)

(10,)


In [13]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
arr = np.arange(25,55).reshape(5,6)
arr

#  while reshaping an array, no. of elements in an array and product of rows and columns should match while reshaping.

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [16]:
arr = np.arange(25,55).reshape(5,7)
arr

ValueError: cannot reshape array of size 30 into shape (5,7)

In [17]:
arr = np.arange(25,55).reshape(15,2)
arr

array([[25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54]])

# Reshaping using shape attribute

In [20]:
# Reshaping using shape attribute
# Shape will make changes to the existing object
arr.shape

(5, 6)

In [21]:
arr.shape = 2,15
arr

array([[25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54]])

In [35]:
arr.shape = 2,5,3
arr

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

# Converting Higher Dimensional array(2D or 3D) to 1D array

In [36]:
arr

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [37]:
arr.ravel()

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [38]:
arr1 =arr.ravel()

In [39]:
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
       42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54])

In [40]:
# Any one dimension either row, or column or rank can be -negative
arr1.reshape(5,-1)

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [41]:
arr1.reshape(-1,5)

array([[25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [42]:
arr1.reshape(-10,2)

array([[25, 26],
       [27, 28],
       [29, 30],
       [31, 32],
       [33, 34],
       [35, 36],
       [37, 38],
       [39, 40],
       [41, 42],
       [43, 44],
       [45, 46],
       [47, 48],
       [49, 50],
       [51, 52],
       [53, 54]])

In [43]:
arr1.reshape(2,5,-1)

array([[[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36],
        [37, 38, 39]],

       [[40, 41, 42],
        [43, 44, 45],
        [46, 47, 48],
        [49, 50, 51],
        [52, 53, 54]]])

In [44]:
arr1.reshape(2,-10,-1)

ValueError: can only specify one unknown dimension

# Reshaping an array using Transposing an array

In [46]:
# Transpose - Converting row to columns and columns to rows

print(arr)
print()
print()
print()
print(arr.T)


[[[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]
  [37 38 39]]

 [[40 41 42]
  [43 44 45]
  [46 47 48]
  [49 50 51]
  [52 53 54]]]



[[[25 40]
  [28 43]
  [31 46]
  [34 49]
  [37 52]]

 [[26 41]
  [29 44]
  [32 47]
  [35 50]
  [38 53]]

 [[27 42]
  [30 45]
  [33 48]
  [36 51]
  [39 54]]]


In [51]:
print(arr)
print()
print()
print(arr.T)

[[25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]
 [49 50 51 52 53 54]]


[[25 31 37 43 49]
 [26 32 38 44 50]
 [27 33 39 45 51]
 [28 34 40 46 52]
 [29 35 41 47 53]
 [30 36 42 48 54]]


# Basic Operations on the array

In [ ]:
# Basic Operations on the array
# Arithmetic, Comparison, Equality

In [52]:
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [53]:
arr2 = np.array([11,22,33,44,55])
arr2

array([11, 22, 33, 44, 55])

In [54]:
arr1 + arr2   # This is an element wise addition

array([ 21,  42,  63,  84, 105])

In [55]:
arr1 * arr2

array([ 110,  440,  990, 1760, 2750])

In [56]:
arr1 / 2

array([ 5., 10., 15., 20., 25.])

In [57]:
arr1 % 2

array([0, 0, 0, 0, 0], dtype=int32)

In [58]:
arr1 > 30

array([False, False, False,  True,  True])

# Multiplication

In [69]:
# Multiplication on an array
     # Scalar multiplication
     # Vector Multiplication - dot product
        

# Scalar product
# print(arr1 *3)
# print(arr1 * arr2) # shape of both the arrays should be same


# Vector product - dor(arr1,arr2)
# np.dot(arr1,arr2)

# Vector product in 2D arrays
# No of coulmn in arr1 and no of rows in arr2 should be same
# The resultant array will have the shape as (no of rows in arr1 X no of column in arr2)


arr1 = np.arange(25,55).reshape(5,6)
arr2 = np.arange(1,37).reshape(6,6)
np.dot(arr1,arr2)

array([[2745, 2910, 3075, 3240, 3405, 3570],
       [3321, 3522, 3723, 3924, 4125, 4326],
       [3897, 4134, 4371, 4608, 4845, 5082],
       [4473, 4746, 5019, 5292, 5565, 5838],
       [5049, 5358, 5667, 5976, 6285, 6594]])

# compound assignment operation

In [66]:
arr1 += 2
arr1

array([[27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55, 56]])

In [67]:
arr1 &=2 
arr1

array([[2, 0, 0, 2, 2, 0],
       [0, 2, 2, 0, 0, 2],
       [2, 0, 0, 2, 2, 0],
       [0, 2, 2, 0, 0, 2],
       [2, 0, 0, 2, 2, 0]])

# Unary operations

In [70]:
# Unary operations - sum(), max,min
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [71]:
arr1.sum()

1185

In [72]:
# Finding the sum of array elements in each row
arr1

# Sum of all the elements in the arr1 along the rows
# It will add all the element in individual along from each row and then adds them up
# np.sum(arr1, axis = 0)






# Sum of all the elements in the arr1 along the column
# np.sum(arr1, axis = 1)

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [73]:
arr1.sum(axis = 0)

array([185, 190, 195, 200, 205, 210])

In [74]:
arr1.sum(axis = 1)

array([165, 201, 237, 273, 309])

In [ ]:
# Finding the max value of array elements in each row

In [75]:
arr1.max()

54

In [76]:
arr1.max(axis = 0)

array([49, 50, 51, 52, 53, 54])

In [77]:
arr1.max(axis = 1)

array([30, 36, 42, 48, 54])

# Comparison operator

In [78]:
# Comparison Operation - Return Boolean matrix
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [79]:
arr1 > 32

array([[False, False, False, False, False, False],
       [False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True]])

In [81]:
arr1.reshape(6,5) >32

array([[False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

# Indexing and Slicing

In [83]:
arr1 = np.arange(25,35)
arr1

array([25, 26, 27, 28, 29, 30, 31, 32, 33, 34])

In [85]:
arr1[0]

25

In [86]:
arr1[-1]

34

In [87]:
arr1[2:6]

array([27, 28, 29, 30])

In [88]:
arr1[2:6:2]

array([27, 29])

In [89]:
arr1[::-1]

array([34, 33, 32, 31, 30, 29, 28, 27, 26, 25])

# Indexing and slicing in 2d Array

In [92]:
#on 2D array

arr2 = np.arange(25,61).reshape(6, 6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [ ]:
# While performing indexing or slicing on an array, the first element should be a row and second element should be column
# Indexing - arr_name[row][col]/arr_name[row,col] - To access individual element
# arr_name[row] - the complete row from the 2d Array
# print(arr2[2][2])
# print(arr2[2,2]

In [93]:
arr2[0]

array([25, 26, 27, 28, 29, 30])

In [94]:
arr2[-1]

array([55, 56, 57, 58, 59, 60])

In [95]:
arr2[::,1]

array([26, 32, 38, 44, 50, 56])

In [96]:
arr2[::,-1]

array([30, 36, 42, 48, 54, 60])

In [97]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [98]:
arr2[2,2]

39

In [99]:
arr2[2][2]

39

In [102]:
arr3 =np.arange(25,61).reshape(3,3,4)
arr3

array([[[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]],

       [[37, 38, 39, 40],
        [41, 42, 43, 44],
        [45, 46, 47, 48]],

       [[49, 50, 51, 52],
        [53, 54, 55, 56],
        [57, 58, 59, 60]]])

In [103]:
arr3[1]

array([[37, 38, 39, 40],
       [41, 42, 43, 44],
       [45, 46, 47, 48]])

In [104]:
arr3[1][1]

array([41, 42, 43, 44])

In [105]:
arr3[1][1][1]

42

In [106]:
arr3[1,1,1]

42

In [107]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [109]:
arr2[2][3:6]

array([40, 41, 42])

In [110]:
arr2[4][3:6]

array([52, 53, 54])

In [111]:
arr2[5][3:6]

array([58, 59, 60])

In [121]:
arr2[3:,3:]

array([[46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])

In [120]:
arr2[3::,3:]

array([[46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])

In [122]:
arr2[3:6,3:6]

array([[46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])

In [123]:
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [129]:
arr2[1:4:2,::2]

array([[31, 33, 35],
       [43, 45, 47]])

In [130]:
# [33,38,45,40]
row_index = [1,2,3,2]
col_index = [2,1,2,3]
arr2[row_index,col_index]

array([33, 38, 45, 40])