In [1]:
import numpy as np

# Indexing and Slicing

In [6]:
emp_name = np.array(['Jash Vikas Shah',
                    'Sushil Kumar',
                    'MAYANK MISHRA',
                    'Mohammed Yomeen Rafeeq',
                    'NIKHIL BABURAO BURDE',
                    'Padmaraj',
                    'Jagadeshvaran',
                    'Mirza Mustaba Hussain',
                    'Chiranth HG',
                    'Rashi Navalgund',
                    'Manoj Kumar',
                    'DEBANSHU MONDAL']).reshape(3, 4)

In [7]:
emp_name

array([['Jash Vikas Shah', 'Sushil Kumar', 'MAYANK MISHRA',
        'Mohammed Yomeen Rafeeq'],
       ['NIKHIL BABURAO BURDE', 'Padmaraj', 'Jagadeshvaran',
        'Mirza Mustaba Hussain'],
       ['Chiranth HG', 'Rashi Navalgund', 'Manoj Kumar',
        'DEBANSHU MONDAL']], dtype='<U22')

In [9]:
row_lst =[0,1,2,2]
col_lst =[0,1,1,3]
emp_name[row_lst,col_lst] =np.NaN
emp_name

array([['nan', 'Sushil Kumar', 'MAYANK MISHRA', 'Mohammed Yomeen Rafeeq'],
       ['NIKHIL BABURAO BURDE', 'nan', 'Jagadeshvaran',
        'Mirza Mustaba Hussain'],
       ['Chiranth HG', 'nan', 'Manoj Kumar', 'nan']], dtype='<U22')

# Index with Boolean Array

In [51]:
age = np.random.randint(18,60,30).reshape(5,6)
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [21]:
age > 30

array([[ True, False,  True,  True,  True, False],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True, False, False,  True,  True],
       [ True, False,  True, False, False,  True],
       [False,  True,  True,  True,  True,  True]])

In [22]:
age < 30

array([[False,  True, False, False, False,  True],
       [False, False, False, False, False, False],
       [False, False,  True,  True, False, False],
       [False,  True, False,  True,  True, False],
       [ True, False, False, False, False, False]])

In [15]:
age [age > 30]

array([50, 33, 35, 40, 36, 57, 43, 49, 44, 35, 54, 40, 36, 42, 39, 44, 44,
       52, 39, 43, 43, 58, 51])

In [16]:
age [age < 30]

array([25, 21, 23, 24, 19, 21, 28])

In [41]:
# Python - Numpy
# and    -  &
# or     -  |
# not    -  ~



age [(age > 30) & (age < 50)]

array([47, 47, 47, 45, 36, 45, 32, 36, 38, 42, 38, 40])

In [38]:
age

array([[21, 25, 54, 47, 47, 47],
       [51, 45, 54, 29, 36, 55],
       [45, 58, 57, 32, 36, 58],
       [27, 38, 54, 24, 18, 22],
       [42, 38, 40, 55, 23, 55]])

In [ ]:
[47,51,36,57,22,38]

In [39]:
row_lst = [0,1,2,2,3,4]
col_lst = [3,0,4,2,5,1]
age[row_lst,col_lst]

array([47, 51, 36, 57, 22, 38])

In [42]:
# index of all those values which are greater than 30
np.where(age > 30)

(array([0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 4, 4, 4, 4, 4],
       dtype=int64),
 array([2, 3, 4, 5, 0, 1, 2, 4, 5, 0, 1, 2, 3, 4, 5, 1, 2, 0, 1, 2, 3, 5],
       dtype=int64))

In [44]:
age[np.where(age > 30)]

array([54, 47, 47, 47, 51, 45, 54, 36, 55, 45, 58, 57, 32, 36, 58, 38, 54,
       42, 38, 40, 55, 55])

In [56]:
# Finding the maximum value in an array
# age.max()
# np.max(age)

# Finding the index of maximum value in an array
# np.argmax(age)
# np.argmax(age, axis = 1)

# Finding the row and column index of maximum value in 2d array 
np.where(age == 44)
# np.where(age == np.max(age))
np.where(age == np.max(age))

(array([4], dtype=int64), array([1], dtype=int64))

In [253]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [254]:
np.max(age, axis =0)

array([46, 56, 53, 55, 51, 52])

In [255]:
np.max(age, axis =1)

array([55, 47, 53, 55, 56])

In [60]:
np.argmax(age, axis =0)

array([0, 4, 2, 0, 3, 4], dtype=int64)

In [61]:
np.argmax(age, axis =1)

array([3, 3, 2, 3, 1], dtype=int64)

In [62]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [64]:
arr1 = np.arange(25,55).reshape(5,6)

In [65]:
arr1

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54]])

In [68]:
np.argmax(arr1, axis =0)

array([4, 4, 4, 4, 4, 4], dtype=int64)

In [69]:
np.argmax(arr1, axis =1)

array([5, 5, 5, 5, 5], dtype=int64)

In [73]:
arr2 =np.arange(25,61).reshape(6,6)
arr2

array([[25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36],
       [37, 38, 39, 40, 41, 42],
       [43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60]])

In [79]:
arr2[3:,3:]

array([[46, 47, 48],
       [52, 53, 54],
       [58, 59, 60]])

In [84]:
arr2[1:4:2,0:5:2]

array([[31, 33, 35],
       [43, 45, 47]])

In [85]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [89]:
age.max(axis =0)

array([46, 56, 53, 55, 51, 52])

In [91]:
age.argmax(axis =0)

array([0, 4, 2, 0, 3, 4], dtype=int64)

In [90]:
age.max(axis =1)

array([55, 47, 53, 55, 56])

In [93]:
np.argmax(age, axis =1)

array([3, 3, 2, 3, 1], dtype=int64)

In [88]:
age.sum(axis =0)
# when axis = 0(It takes the element form each row and does the summation(first element from each row,
# second element from each row and third element from each row and so on..))
# so, element from each row, that is where axis =0 represents rows

# when axis = 1(It takes the element form each column and does the summation(first element from each column,
# second element from each column and third element from each column and so on..))
# so, element from each column, that is where axis =1 represents columns


array([198, 220, 186, 235, 198, 158])

In [94]:
np.argmax(age, axis =0)

array([0, 4, 2, 0, 3, 4], dtype=int64)

In [95]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [101]:
arr3 = np.random.randint(25,61,30)
arr3.reshape(5,6)

array([[54, 45, 47, 54, 37, 49],
       [33, 29, 26, 59, 30, 48],
       [27, 37, 58, 51, 58, 53],
       [44, 60, 38, 25, 54, 43],
       [36, 56, 57, 26, 48, 44]])

In [102]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [103]:
# Count the toltal number of elements which are greater than 30
age > 30

array([[ True,  True, False,  True,  True, False],
       [ True,  True, False,  True, False, False],
       [ True, False,  True,  True,  True, False],
       [False,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False,  True]])

In [105]:
np.sum(age>30)

20

In [107]:
np.sum(age[age>30])

951

In [ ]:
# Find the count of all those element which are greater than 30 along rows
print(np.sum(age>30,axis=0))
# Find the count of all those element which are greater than 30 along cols
print(np.sum(age>30,axis=1))

In [115]:
np.sum((age > 30), axis =0)

array([4, 4, 3, 4, 3, 2])

In [121]:
# np.sum(age[age>30, axis =0])
np.sum(age[age>30], axis =0)

951

In [125]:
age.ndim

2

In [131]:
np.sum(age > 30, axis =1)

array([4, 3, 4, 5, 4])

In [132]:
# np.sum(age[age > 30], axis =1)
np.sum(age>30)

20

In [114]:
age

array([[46, 44, 25, 55, 47, 21],
       [44, 45, 23, 47, 21, 19],
       [40, 25, 53, 50, 49, 27],
       [25, 50, 45, 55, 51, 39],
       [43, 56, 40, 28, 30, 52]])

In [133]:
# np.all(cond) - It check sfor the condition for all the elements in the array 
# returns True if all the elements are satisfying the condition else returns False
np.all(age>30)

False

In [134]:
np.all(age>10)

True

In [135]:
# np.any(cond) - It check for the condition for all the elements in the array 
# returns True if any one of the elements is satisfying the condition else returns False
np.any(age>30)

True

In [136]:
np.any(age > 60)

False

In [256]:
arr1 = np.random.randint(1,50,125).reshape(5,5,5)

In [257]:
arr1

array([[[44, 24, 49, 24, 25],
        [29, 48, 35, 48, 33],
        [44,  9, 37,  9, 21],
        [ 6, 30, 33, 20, 38],
        [36, 35,  8, 22,  6]],

       [[46, 49, 24, 35, 10],
        [25, 44, 30, 29,  3],
        [ 6, 36, 15, 47, 10],
        [34, 38, 36, 20, 15],
        [47, 33, 11, 11, 28]],

       [[32, 34,  9,  2, 20],
        [22, 47,  8, 32, 25],
        [32, 25, 14, 37, 17],
        [47,  9,  9, 39, 39],
        [23,  3,  3, 34, 49]],

       [[ 2, 35,  8,  3, 11],
        [38, 23, 24, 19,  3],
        [ 1,  2, 20,  9, 47],
        [21, 28, 37,  6, 17],
        [46, 43, 12,  1, 43]],

       [[ 3, 18, 22, 38, 35],
        [19, 16, 47, 25, 28],
        [47, 47, 21, 16, 34],
        [41,  4, 44, 15, 36],
        [14, 38, 27, 19, 19]]])

In [258]:
np.array((arr1[0, 2, 1], arr1[1, 2, 3], arr1[4, 0, 0]))

array([ 9, 47,  3])

# Iteration over the array

In [141]:
arr1 =np.random.randint(1,50,30)
for i in arr1:
    print(i)

15
49
8
18
16
42
34
4
44
38
8
49
26
17
12
47
29
18
45
32
27
29
23
29
42
3
35
30
15
36


In [142]:
arr2 = arr1.reshape(5,6)
arr2

array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]])

In [145]:
for row in arr2:
    for ele in row:
        print(ele)

15
49
8
18
16
42
34
4
44
38
8
49
26
17
12
47
29
18
45
32
27
29
23
29
42
3
35
30
15
36


In [146]:
for ele in arr2.ravel():
    print(ele)

15
49
8
18
16
42
34
4
44
38
8
49
26
17
12
47
29
18
45
32
27
29
23
29
42
3
35
30
15
36


In [148]:
for ele in np.nditer(arr2):
    print(ele)

15
49
8
18
16
42
34
4
44
38
8
49
26
17
12
47
29
18
45
32
27
29
23
29
42
3
35
30
15
36


In [150]:
for ele in np.nditer(arr2, order = 'C'):   # Row wise
    print(ele)

15
49
8
18
16
42
34
4
44
38
8
49
26
17
12
47
29
18
45
32
27
29
23
29
42
3
35
30
15
36


In [151]:
arr2

array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]])

In [152]:

for ele in np.nditer(arr2, order = 'F'):   # column wise
    print(ele)

15
34
26
45
42
49
4
17
32
3
8
44
12
27
35
18
38
47
29
30
16
8
29
23
15
42
49
18
29
36


In [163]:
arr2

array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]])

In [164]:
arr2 < 18

array([[ True, False,  True, False,  True, False],
       [False,  True, False, False,  True, False],
       [False,  True,  True, False, False, False],
       [False, False, False, False, False, False],
       [False,  True, False, False,  True, False]])

In [167]:
np.where(age<18, np.NaN, arr2)

array([[15., 49.,  8., 18., 16., 42.],
       [34.,  4., 44., 38.,  8., 49.],
       [26., 17., 12., 47., 29., 18.],
       [45., 32., 27., 29., 23., 29.],
       [42.,  3., 35., 30., 15., 36.]])

In [174]:
arr2 =np.array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]] ,dtype = float)



for ele in np.nditer(arr2, op_flags = ['readwrite']):
    if ele < 18:
        ele[...] = np.NaN                     # NaN is a folat value
print(arr2)


[[nan 49. nan 18. nan 42.]
 [34. nan 44. 38. nan 49.]
 [26. nan nan 47. 29. 18.]
 [45. 32. 27. 29. 23. 29.]
 [42. nan 35. 30. nan 36.]]


In [177]:
arr2 =np.array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]] ,dtype = float)



for ele in np.nditer(arr2, op_flags = ['readwrite']):
    if ele < 18:
        ele[...] = 0                     # NaN is a folat value
    else:
        ele[...] = ele+10
print(arr2)


[[ 0. 59.  0. 28.  0. 52.]
 [44.  0. 54. 48.  0. 59.]
 [36.  0.  0. 57. 39. 28.]
 [55. 42. 37. 39. 33. 39.]
 [52.  0. 45. 40.  0. 46.]]


In [178]:
arr2 =np.array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]] ,dtype = float)



for ele in np.nditer(arr2, op_flags = ['readonly']):
    if ele < 18:
        ele[...] = 0                     # NaN is a folat value
    else:
        ele[...] = ele+10
print(arr2)


ValueError: assignment destination is read-only

In [179]:
arr2 =np.array([[15, 49,  8, 18, 16, 42],
       [34,  4, 44, 38,  8, 49],
       [26, 17, 12, 47, 29, 18],
       [45, 32, 27, 29, 23, 29],
       [42,  3, 35, 30, 15, 36]] ,dtype = float)



for ele in np.nditer(arr2, op_flags = ['writeonly']):
    if ele < 18:
        ele[...] = 0                     # NaN is a folat value
    else:
        ele[...] = ele+10
print(arr2)


[[ 0. 59.  0. 28.  0. 52.]
 [44.  0. 54. 48.  0. 59.]
 [36.  0.  0. 57. 39. 28.]
 [55. 42. 37. 39. 33. 39.]
 [52.  0. 45. 40.  0. 46.]]


# Splitting of array

In [232]:
arr1

array([33, 32, 35, 24, 45, 25, 44, 20, 30, 55, 25, 26, 42, 48, 21, 28, 36,
       41, 22, 29, 30, 36, 22, 38, 27, 22, 38, 55, 30, 42, 21, 31, 41, 30,
       30, 53])

In [233]:
len(arr1)

36

In [234]:
np.split(arr1, 6)

[array([33, 32, 35, 24, 45, 25]),
 array([44, 20, 30, 55, 25, 26]),
 array([42, 48, 21, 28, 36, 41]),
 array([22, 29, 30, 36, 22, 38]),
 array([27, 22, 38, 55, 30, 42]),
 array([21, 31, 41, 30, 30, 53])]

In [183]:
np.split(arr1, 4)

ValueError: array split does not result in an equal division

In [235]:
arr1 = np.random.randint(20,56,36)
arr1

array([52, 35, 54, 42, 47, 37, 36, 38, 35, 22, 53, 35, 37, 28, 28, 54, 34,
       48, 21, 27, 43, 53, 28, 54, 40, 47, 52, 43, 48, 53, 30, 36, 51, 52,
       40, 46])

In [236]:
np.split(arr1, [2,5,9,14,20])

[array([52, 35]),
 array([54, 42, 47]),
 array([37, 36, 38, 35]),
 array([22, 53, 35, 37, 28]),
 array([28, 54, 34, 48, 21, 27]),
 array([43, 53, 28, 54, 40, 47, 52, 43, 48, 53, 30, 36, 51, 52, 40, 46])]

In [237]:
arr2 = arr1.reshape(6,6)

In [238]:
arr2

array([[52, 35, 54, 42, 47, 37],
       [36, 38, 35, 22, 53, 35],
       [37, 28, 28, 54, 34, 48],
       [21, 27, 43, 53, 28, 54],
       [40, 47, 52, 43, 48, 53],
       [30, 36, 51, 52, 40, 46]])

In [239]:
np.split(arr2,3)

[array([[52, 35, 54, 42, 47, 37],
        [36, 38, 35, 22, 53, 35]]),
 array([[37, 28, 28, 54, 34, 48],
        [21, 27, 43, 53, 28, 54]]),
 array([[40, 47, 52, 43, 48, 53],
        [30, 36, 51, 52, 40, 46]])]

In [240]:
np.split(arr2,3, axis =0)

[array([[52, 35, 54, 42, 47, 37],
        [36, 38, 35, 22, 53, 35]]),
 array([[37, 28, 28, 54, 34, 48],
        [21, 27, 43, 53, 28, 54]]),
 array([[40, 47, 52, 43, 48, 53],
        [30, 36, 51, 52, 40, 46]])]

In [241]:
arr2

array([[52, 35, 54, 42, 47, 37],
       [36, 38, 35, 22, 53, 35],
       [37, 28, 28, 54, 34, 48],
       [21, 27, 43, 53, 28, 54],
       [40, 47, 52, 43, 48, 53],
       [30, 36, 51, 52, 40, 46]])

In [242]:
np.split(arr2,3, axis =1)

[array([[52, 35],
        [36, 38],
        [37, 28],
        [21, 27],
        [40, 47],
        [30, 36]]),
 array([[54, 42],
        [35, 22],
        [28, 54],
        [43, 53],
        [52, 43],
        [51, 52]]),
 array([[47, 37],
        [53, 35],
        [34, 48],
        [28, 54],
        [48, 53],
        [40, 46]])]

In [243]:
arr2

array([[52, 35, 54, 42, 47, 37],
       [36, 38, 35, 22, 53, 35],
       [37, 28, 28, 54, 34, 48],
       [21, 27, 43, 53, 28, 54],
       [40, 47, 52, 43, 48, 53],
       [30, 36, 51, 52, 40, 46]])

In [248]:
np.split(arr2, [0,3], axis =0)

[array([], shape=(0, 6), dtype=int32),
 array([[52, 35, 54, 42, 47, 37],
        [36, 38, 35, 22, 53, 35],
        [37, 28, 28, 54, 34, 48]]),
 array([[21, 27, 43, 53, 28, 54],
        [40, 47, 52, 43, 48, 53],
        [30, 36, 51, 52, 40, 46]])]

In [249]:
np.split(arr2, [1,3], axis =0)

[array([[52, 35, 54, 42, 47, 37]]),
 array([[36, 38, 35, 22, 53, 35],
        [37, 28, 28, 54, 34, 48]]),
 array([[21, 27, 43, 53, 28, 54],
        [40, 47, 52, 43, 48, 53],
        [30, 36, 51, 52, 40, 46]])]

In [251]:
arr2

array([[52, 35, 54, 42, 47, 37],
       [36, 38, 35, 22, 53, 35],
       [37, 28, 28, 54, 34, 48],
       [21, 27, 43, 53, 28, 54],
       [40, 47, 52, 43, 48, 53],
       [30, 36, 51, 52, 40, 46]])

In [250]:
np.split(arr2, [1,3], axis =1)

[array([[52],
        [36],
        [37],
        [21],
        [40],
        [30]]),
 array([[35, 54],
        [38, 35],
        [28, 28],
        [27, 43],
        [47, 52],
        [36, 51]]),
 array([[42, 47, 37],
        [22, 53, 35],
        [54, 34, 48],
        [53, 28, 54],
        [43, 48, 53],
        [52, 40, 46]])]

In [252]:
np.split(arr2, [0,3,5], axis =1)

[array([], shape=(6, 0), dtype=int32),
 array([[52, 35, 54],
        [36, 38, 35],
        [37, 28, 28],
        [21, 27, 43],
        [40, 47, 52],
        [30, 36, 51]]),
 array([[42, 47],
        [22, 53],
        [54, 34],
        [53, 28],
        [43, 48],
        [52, 40]]),
 array([[37],
        [35],
        [48],
        [54],
        [53],
        [46]])]

In [210]:
arr2

array([[49, 46, 44, 44, 23, 23],
       [27, 32, 47, 25, 42, 54],
       [26, 53, 28, 25, 47, 44],
       [26, 52, 22, 47, 34, 32],
       [51, 49, 49, 36, 20, 51],
       [22, 29, 27, 48, 33, 42]])

# Vectorization

In [211]:
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

In [212]:
arr2 = np.array([11,22,33,44,55])
arr2

array([11, 22, 33, 44, 55])

In [213]:
#[110,42,990,84,2750]
arr1* arr2


array([ 110,  440,  990, 1760, 2750])

In [214]:
arr1 + arr2

array([ 21,  42,  63,  84, 105])

In [215]:
np.where(arr1)

(array([0, 1, 2, 3, 4], dtype=int64),)

In [217]:

def multi_add(x, y):
    if list(arr1).index(x)%2 ==0:
        return x*y
    else:
        return x+y

multi_add_vector = np.vectorize(multi_add)

multi_add_vector(arr1, arr2)

array([ 110,   42,  990,   84, 2750])

In [221]:

def multi_add(num1, num2):
    ind = list(arr1).index(num1)
    if ind%2 == 0:
        return num1*num2
    else:
        return num1+num2

multi_add_vector = np.vectorize(multi_add)

multi_add_vector(arr1, arr2)

array([ 110,   42,  990,   84, 2750])

In [223]:
np.argwhere(arr1)%2 ==0

array([[ True],
       [False],
       [ True],
       [False],
       [ True]])

In [228]:
def multi_add(x, y):
    if np.argwhere(arr1)%2 ==0:
        return x*y
    else:
        return x+y

multi_add_vector = np.vectorize(multi_add)

multi_add_vector(arr1, arr2)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()